*java.rmi.server.ServerCloneException* *ServerCloneException* A ServerCloneException is thrown if a remote exception occurs
 during the cloning of a UnicastRemoteObject.

public class ServerCloneException
  extends    |java.lang.CloneNotSupportedException|

|java.rmi.server.ServerCloneException_Description|
|java.rmi.server.ServerCloneException_Fields|
|java.rmi.server.ServerCloneException_Constructors|
|java.rmi.server.ServerCloneException_Methods|

====================================================================================================================================================================================

*java.rmi.server.ServerCloneException_Fields*
|java.lang.Exception_java.rmi.server.ServerCloneException.detail|

*java.rmi.server.ServerCloneException_Constructors*
|java.rmi.server.ServerCloneException(String)|Constructs a ServerCloneException with the specified  detail message.
|java.rmi.server.ServerCloneException(String,Exception)|Constructs a ServerCloneException with the specified  detail message and cause.

*java.rmi.server.ServerCloneException_Methods*
|java.rmi.server.ServerCloneException.getCause()|Returns the cause of this exception.
|java.rmi.server.ServerCloneException.getMessage()|Returns the detail message, including the message from the cause, if  any, of this exception.

*java.rmi.server.ServerCloneException_Description*

A ServerCloneException is thrown if a remote exception occurs during the cloning of a UnicastRemoteObject. 

As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "nested exception" that may be provided at construction 
time and accessed via the public (|java.rmi.server.ServerCloneException|) field is now known as the cause, and may be accessed via the (|java.lang.Throwable|) method, as well as 
the aforementioned "legacy field." 

Invoking the method (|java.lang.Throwable|) on an instance of ServerCloneException always throws (|java.lang.IllegalStateException|) . 



*java.lang.Exception_java.rmi.server.ServerCloneException.detail*

The cause of the exception. 

This field predates the general-purpose exception chaining facility. The (|java.lang.Throwable|) method is now the preferred means of obtaining this information. 



*java.rmi.server.ServerCloneException(String)*

public ServerCloneException(java.lang.String s)

Constructs a ServerCloneException with the specified detail message. 

    s - the detail message. 

*java.rmi.server.ServerCloneException(String,Exception)*

public ServerCloneException(
  java.lang.String s,
  java.lang.Exception cause)

Constructs a ServerCloneException with the specified detail message and cause. 

    s - the detail message. 
    cause - the cause 

*java.rmi.server.ServerCloneException.getCause()*

public |java.lang.Throwable| getCause()

Returns the cause of this exception. This method returns the value of the (|java.rmi.server.ServerCloneException|) field. 



    Returns: the cause, which may be null. 

*java.rmi.server.ServerCloneException.getMessage()*

public |java.lang.String| getMessage()

Returns the detail message, including the message from the cause, if any, of this exception. 



    Returns: the detail message 


