*java.util.concurrent.RejectedExecutionException* *RejectedExecutionException* E

public class RejectedExecutionException
  extends    |java.lang.RuntimeException|

|java.util.concurrent.RejectedExecutionException_Description|
|java.util.concurrent.RejectedExecutionException_Fields|
|java.util.concurrent.RejectedExecutionException_Constructors|
|java.util.concurrent.RejectedExecutionException_Methods|

================================================================================

*java.util.concurrent.RejectedExecutionException_Constructors*
|java.util.concurrent.RejectedExecutionException()|Constructs a RejectedExecuti
|java.util.concurrent.RejectedExecutionException(String)|Constructs a RejectedE
|java.util.concurrent.RejectedExecutionException(String,Throwable)|Constructs a
|java.util.concurrent.RejectedExecutionException(Throwable)|Constructs a Reject

*java.util.concurrent.RejectedExecutionException_Description*

Exception thrown by an (|java.util.concurrent.Executor|) when a task cannot be 
accepted for execution. 


*java.util.concurrent.RejectedExecutionException()*

public RejectedExecutionException()

Constructs a RejectedExecutionException with no detail message. The cause is 
not initialized, and may subsequently be initialized by a call to 
initCause(|java.util.concurrent.RejectedExecutionException|) . 


*java.util.concurrent.RejectedExecutionException(String)*

public RejectedExecutionException(java.lang.String message)

Constructs a RejectedExecutionException with the specified detail message. The 
cause is not initialized, and may subsequently be initialized by a call to 
initCause(|java.util.concurrent.RejectedExecutionException|) . 

    message - the detail message 

*java.util.concurrent.RejectedExecutionException(String,Throwable)*

public RejectedExecutionException(
  java.lang.String message,
  java.lang.Throwable cause)

Constructs a RejectedExecutionException with the specified detail message and 
cause. 

    message - the detail message 
    cause - the cause (which is saved for later retrieval by the {@link #getCause()} 
       method) 

*java.util.concurrent.RejectedExecutionException(Throwable)*

public RejectedExecutionException(java.lang.Throwable cause)

Constructs a RejectedExecutionException with the specified cause. The detail 
message is set to: (cause == null ? null : cause.toString()) (which typically 
contains the class and detail message of cause). 

    cause - the cause (which is saved for later retrieval by the {@link #getCause()} 
       method) 

