*java.lang.ExceptionInInitializerError* *ExceptionInInitializerError* Signals th

public class ExceptionInInitializerError
  extends    |java.lang.LinkageError|

|java.lang.ExceptionInInitializerError_Description|
|java.lang.ExceptionInInitializerError_Fields|
|java.lang.ExceptionInInitializerError_Constructors|
|java.lang.ExceptionInInitializerError_Methods|

================================================================================

*java.lang.ExceptionInInitializerError_Constructors*
|java.lang.ExceptionInInitializerError()|Constructs an ExceptionInInitializerEr
|java.lang.ExceptionInInitializerError(String)|Constructs an ExceptionInInitial
|java.lang.ExceptionInInitializerError(Throwable)|Constructs a new ExceptionInI

*java.lang.ExceptionInInitializerError_Methods*
|java.lang.ExceptionInInitializerError.getCause()|Returns the cause of this err
|java.lang.ExceptionInInitializerError.getException()|Returns the exception tha

*java.lang.ExceptionInInitializerError_Description*

Signals that an unexpected exception has occurred in a static initializer. An 
ExceptionInInitializerError is thrown to indicate that an exception occurred 
during evaluation of a static initializer or the initializer for a static 
variable. 

As of release 1.4, this exception has been retrofitted to conform to the 
general purpose exception-chaining mechanism. The "saved throwable object" that 
may be provided at construction time and accessed via the 
(|java.lang.ExceptionInInitializerError|) method is now known as the cause, and 
may be accessed via the (|java.lang.Throwable|) method, as well as the 
aforementioned "legacy method." 


*java.lang.ExceptionInInitializerError()*

public ExceptionInInitializerError()

Constructs an ExceptionInInitializerError with null as its detail message 
string and with no saved throwable object. A detail message is a String that 
describes this particular exception. 


*java.lang.ExceptionInInitializerError(String)*

public ExceptionInInitializerError(java.lang.String s)

Constructs an ExceptionInInitializerError with the specified detail message 
string. A detail message is a String that describes this particular exception. 
The detail message string is saved for later retrieval by the 
(|java.lang.Throwable|) method. There is no saved throwable object. 

    s - the detail message 

*java.lang.ExceptionInInitializerError(Throwable)*

public ExceptionInInitializerError(java.lang.Throwable thrown)

Constructs a new ExceptionInInitializerError class by saving a reference to the 
Throwable object thrown for later retrieval by the 
(|java.lang.ExceptionInInitializerError|) method. The detail message string is 
set to null. 

    thrown - The exception thrown 

*java.lang.ExceptionInInitializerError.getCause()*

public |java.lang.Throwable| getCause()

Returns the cause of this error (the exception that occurred during a static 
initialization that caused this error to be created). 


    Returns: the cause of this error or null if the cause is nonexistent or unknown. 
*java.lang.ExceptionInInitializerError.getException()*

public |java.lang.Throwable| getException()

Returns the exception that occurred during a static initialization that caused 
this error to be created. 

This method predates the general-purpose exception chaining facility. The 
(|java.lang.Throwable|) method is now the preferred means of obtaining this 
information. 


    Returns: the saved throwable object of this ExceptionInInitializerError, or null if this 
             ExceptionInInitializerError has no saved throwable object. 

