*java.lang.reflect.InvocationTargetException* *InvocationTargetException* Invoca

public class InvocationTargetException
  extends    |java.lang.Exception|

|java.lang.reflect.InvocationTargetException_Description|
|java.lang.reflect.InvocationTargetException_Fields|
|java.lang.reflect.InvocationTargetException_Constructors|
|java.lang.reflect.InvocationTargetException_Methods|

================================================================================

*java.lang.reflect.InvocationTargetException_Constructors*
|java.lang.reflect.InvocationTargetException()|Constructs an InvocationTargetEx
|java.lang.reflect.InvocationTargetException(Throwable)|Constructs a Invocation
|java.lang.reflect.InvocationTargetException(Throwable,String)|Constructs a Inv

*java.lang.reflect.InvocationTargetException_Methods*
|java.lang.reflect.InvocationTargetException.getCause()|Returns the cause of th
|java.lang.reflect.InvocationTargetException.getTargetException()|Get the throw

*java.lang.reflect.InvocationTargetException_Description*

InvocationTargetException is a checked exception that wraps an exception thrown 
by an invoked method or constructor. 

As of release 1.4, this exception has been retrofitted to conform to the 
general purpose exception-chaining mechanism. The "target exception" that is 
provided at construction time and accessed via the 
(|java.lang.reflect.InvocationTargetException|) method is now known as the 
cause, and may be accessed via the (|java.lang.Throwable|) method, as well as 
the aforementioned "legacy method." 


*java.lang.reflect.InvocationTargetException()*

protected InvocationTargetException()

Constructs an InvocationTargetException with null as the target exception. 


*java.lang.reflect.InvocationTargetException(Throwable)*

public InvocationTargetException(java.lang.Throwable target)

Constructs a InvocationTargetException with a target exception. 

    target - the target exception 

*java.lang.reflect.InvocationTargetException(Throwable,String)*

public InvocationTargetException(
  java.lang.Throwable target,
  java.lang.String s)

Constructs a InvocationTargetException with a target exception and a detail 
message. 

    target - the target exception 
    s - the detail message 

*java.lang.reflect.InvocationTargetException.getCause()*

public |java.lang.Throwable| getCause()

Returns the cause of this exception (the thrown target exception, which may be 
null). 


    Returns: the cause of this exception. 
*java.lang.reflect.InvocationTargetException.getTargetException()*

public |java.lang.Throwable| getTargetException()

Get the thrown target exception. 

This method predates the general-purpose exception chaining facility. The 
(|java.lang.Throwable|) method is now the preferred means of obtaining this 
information. 


    Returns: the thrown target exception (cause of this exception). 

